### ISSUE TITLE
error CS0122: 'Unsafe' is inaccessible due to its protection level

### ISSUE THREAD

**Issue by d4n3x** [ammariqais/SkiaForUnity#47]
This error pops up right after installing the package into an empty project and wont go away.

"Library/PackageCache/com.ammariqais.skiaforunity@29f8cfa5df/SkiaSharp-Bindings/SKMatrix44.cs(474,4): error CS0122: 'Unsafe' is inaccessible due to its protection level"

Unity Version 2022-3-10f1.

**Comment by ammariqais** [comment]
did you download these dependencies? https://github.com/ammariqais/SkiaForUnity/tree/main/SkiaUnity/Assets/SkiaSharp/Dependencies

**Comment by mhama** [comment]
I also encountered the problem, and fixed by placing the dll.
It would be nice to have the instruction at the top/manual page!
