### ISSUE TITLE
Appstore connect validation fail

### ISSUE THREAD

**Issue by iserofeev** [ammariqais/SkiaForUnity#56]
Hello!

After a successful iOS build, my application works great with all Skia features on real devices. However, when I try to push it to App Store Connect, I face errors: 

**Asset validation failed**
_Unsupported Architectures. The executable for 3D.app/Frameworks/libHarfBuzzSharp.framework contains unsupported architectures '[x86_64, i386]'._

**Asset validation failed**
_Unsupported Architectures. The executable for 3D.app/Frameworks/libSkiaSharp.framework contains unsupported architectures '[x86_64]._

Any ideas how to solve it?
Thanks!

**Comment by ammariqais** [comment]
can you follow this article https://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/

**Comment by zaneclaes** [comment]
This appears to work. @ammariqais a suggestion would be to implement it as a post-build step in the Unity package via the `[PostProcessBuild]` attribute. The specific commands to run (from the xcode directory) are:

```
lipo -remove x86_64 'Frameworks/com.ammariqais.skiaforunity/Library/ios/libSkiaSharp.framework/libSkiaSharp' -o 'Frameworks/com.ammariqais.skiaforunity/Library/ios/libSkiaSharp.framework/libSkiaSharp'
lipo -remove x86_64 -remove i386 'Frameworks/com.ammariqais.skiaforunity/Library/ios/libHarfBuzzSharp.framework/libHarfBuzzSharp' -o 'Frameworks/com.ammariqais.skiaforunity/Library/ios/libHarfBuzzSharp.framework/libHarfBuzzSharp'
```

**Comment by ammariqais** [comment]
> This appears to work. @ammariqais a suggestion would be to implement it as a post-build step in the Unity package via the `[PostProcessBuild]` attribute. The specific commands to run (from the xcode directory) are:
> 
> ```
> lipo -remove x86_64 'Frameworks/com.ammariqais.skiaforunity/Library/ios/libSkiaSharp.framework/libSkiaSharp' -o 'Frameworks/com.ammariqais.skiaforunity/Library/ios/libSkiaSharp.framework/libSkiaSharp'
> lipo -remove x86_64 -remove i386 'Frameworks/com.ammariqais.skiaforunity/Library/ios/libHarfBuzzSharp.framework/libHarfBuzzSharp' -o 'Frameworks/com.ammariqais.skiaforunity/Library/ios/libHarfBuzzSharp.framework/libHarfBuzzSharp'
> ```

thank you for sharing the solution, I updated the frameworks and removed unsupported architectures.

**Comment by ammariqais** [comment]
solved on version 3.1.0

**Comment by zaneclaes** [comment]
Wouldn’t your approach @ammariqais end up dropping support for Intel-based Macs (x86)? I was suggesting it as a post-build step for iOS only to avoid that.

**Comment by ammariqais** [comment]
> Wouldn’t your approach @ammariqais end up dropping support for Intel-based Macs (x86)? I was suggesting it as a post-build step for iOS only to avoid that.

should not affect Intel-based Macs, there is another libs for Mac inside the folder osx
